const userError = {
  NOT_AUTHENTICATED: "NOT_AUTHENTICATED",
  NOT_AUTHORIZED: "NOT_AUTHORIZED",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  PASSWORD_MISMATCH: "PASSWORD_MISMATCH",
  USER_NOT_YET_ACTIVE: "USER_NOT_YET_ACTIVE",
  COULD_NOT_CHANGE_ROLE: "COULD_NOT_CHANGE_ROLE",
  USER_COULD_NOT_BE_AUTHENTICATED: "USER_COULD_NOT_BE_AUTHENTICATED",
  ACCESS_DENIED: "ACCESS_DENIED",
  USER_NOT_ADMIN: "USER_NOT_ADMIN",
  USER_NOT_MODERATOR: "USER_NOT_MODERATOR",
  USER_NOT_EDITOR: "USER_NOT_EDITOR",
  USER_NOT_SUPER_ADMIN: "USER_NOT_SUPER_ADMIN",
  TOKEN_NOT_FOUND: "TOKEN_NOT_FOUND",
};

const roleError = {
  COULD_NOT_CREATE_ROLE: "COULD_NOT_CREATE_ROLE",
  ROLE_NOT_FOUND: "ROLE_NOT_FOUND",
};

const addressError = {
  ADDRESS_NOT_FOUND: "ADDRESS_NOT_FOUND",
};
const databaseError = {
  CONNECTION_FAILED: "CONNECTION_FAILED",
};

const clientError = {
  CLIENT_NOT_FOUND: "CLIENT_NOT_FOUND",
};

export const errors = {
  ...userError,
  ...roleError,
  ...addressError,
  ...databaseError,
  ...clientError,
};

export default errors;
